# http://localhost:4000/bookarts/
# to view locally
title: 'A digital book arts studio not yet otherwise specified :)'
baseurl: /bookarts
url: "https://amandavisconti.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
